Repository CABLE-LSM/CABLE, pull requests merged in 2024-10, with the labels that each got.

#419 One liner fix of leap year bug
  offline/cable_input.F90
Labels: bug

#375 Remove ESM15 case as inconsistent with current input of xkpsorb (#283)
  src/science/casa-cnp/casa_cnp.F90
Labels: priority:high

#410 Fix gfortran compilation and some warnings
  src/offline/cable_mpidrv.F90
  src/offline/cable_mpimaster.F90
  src/offline/cable_mpiworker.F90
  src/offline/cable_write.F90
Labels: bug, code clean-up

#394 Pipe BIOS met data through CRU routines for weather generation
  offline/cable_cru_TRENDY.F90
  offline/cable_driver.F90
  offline/cable_input.F90
Labels: priority:high

#422 Removed ESM15 version with hard-wired xfpleach parameter, #278
  documentation/docs/user_guide/inputs/pftlookup_csv.md
  src/science/casa-cnp/casa_cnp.F90
Labels: priority:high

#430 414 merge am3 miscellaneous science modifications
  src/science/albedo/cbl_snow_albedo.F90
  src/science/misc/cable_carbon.F90
  src/science/radiation/cbl_init_radiation.F90
  src/science/roughness/cable_roughness.F90
  src/science/roughness/roughnessHGT_effLAI_cbl.F90
  src/science/soilsnow/cbl_surfbv.F90
Labels: blocked, priority:high
