Repository CABLE-LSM/CABLE, pull requests merged in 2024-11, with the labels that each got.

#438 431 add routine for more informative namelist errors
  core/biogeophys/cable_common.F90
  core/blaze/blaze.F90
  core/blaze/simfire.F90
  offline/cable_LUC_EXPT.F90
  offline/cable_bios_met_obs_params.F90
  offline/cable_cru_TRENDY.F90
  offline/cable_driver.F90
  offline/cable_plume_mip.F90
  offline/cable_site.F90
Labels: enhancement

#437 219 implement init wetfac as per access3 jules
  CMakeLists.txt
  src/params/cable_other_constants_mod.F90
  src/science/canopy/cbl_SurfaceWetness.F90
  src/science/canopy/cbl_init_wetfac_mod.f90
Labels: priority:medium

#404 402 merge from am3 params
  src/coupled/AM3/control/casa/shared/progs_cnp_vars_mod.F90
  src/offline/cable_parameters.F90
  src/params/cable_other_constants_mod.F90
  src/params/grid_constants_cbl.F90
  src/science/albedo/cbl_snow_albedo.F90
  src/science/misc/cable_carbon.F90
  src/science/roughness/cable_roughness.F90
  src/science/soilsnow/cbl_surfbv.F90
  src/util/cable_runtime_opts_mod.F90
Labels: priority:high

#440 Add initialisation routine for offline drivers
  CMakeLists.txt
  src/offline/cable_driver.F90
  src/offline/cable_driver_init.F90
  src/offline/cable_mpicommon.F90
  src/offline/cable_mpidrv.F90
  src/offline/cable_mpimaster.F90
  src/offline/cable_mpiworker.F90
Labels: code clean-up

#469 Restructure offline drivers
  CMakeLists.txt
  src/offline/cable_cru_TRENDY.F90
  src/offline/cable_driver_init.F90
  src/offline/cable_mpi.F90
  src/offline/cable_mpicommon.F90
  src/offline/cable_mpidrv.F90
  src/offline/cable_mpimaster.F90
  src/offline/cable_mpimaster_stub.F90
  src/offline/cable_mpiworker.F90
  src/offline/cable_mpiworker_stub.F90
  src/offline/cable_offline_driver.F90
  src/offline/cable_output.F90
  src/offline/cable_plume_mip.F90
  src/offline/cable_read.F90
  src/offline/cable_serial.F90
  src/offline/casa_cable.F90
  src/offline/casa_ncdf.F90
  src/offline/cbl_model_driver_offline.F90
  src/science/casa-cnp/casa_feedback.F90
  src/science/casa-cnp/casa_sumcflux.F90
  src/science/gw_hydro/cable_gw_hydro.F90
  src/science/misc/cable_climate.F90
  src/science/pop/POPLUC.F90
  src/science/sli/cable_sli_main.F90
Labels: mpi

#450 exterminate cable_data
  src/coupled/ESM1.5/CABLEfilesFromESM1.5/cable_cbm.F90
  src/coupled/ESM1.5/CABLEfilesFromESM1.5/cable_data.F90
  src/coupled/ESM1.5/CABLEfilesFromESM1.5/cable_explicit_driver.F90
  src/coupled/ESM1.5/CABLEfilesFromESM1.5/cable_hyd_driver.F90
  src/coupled/ESM1.5/CABLEfilesFromESM1.5/cable_implicit_driver.F90
  src/coupled/ESM1.5/CABLEfilesFromESM1.5/cable_um_init_subrs.F90
  src/coupled/ESM1.5/casa_um_inout.F90
  src/science/gw_hydro/cable_gw_hydro.F90
Labels: priority:high

#446 adjust plumbing to USE cable_surface_types offline
  CMakeLists.txt
  src/offline/cable_parameters.F90
  src/offline/cable_surface_types.F90
  src/offline/cbl_model_driver_offline.F90
  src/params/grid_constants_cbl.F90
  src/science/canopy/cbl_SurfaceWetness.F90
  src/science/canopy/cbl_init_wetfac_mod.f90
  src/science/gw_hydro/cable_gw_hydro.F90
  src/science/roughness/cable_roughness.F90
  src/science/soilsnow/cbl_surfbv.F90
Labels: priority:high

#474 changes required for ESM16
  CMakeLists.txt
  src/coupled/ESM1.5/CABLEfilesFromESM1.5/cable_cbm.F90
  src/coupled/ESM1.5/CABLEfilesFromESM1.5/cable_rad_driver.F90
  src/coupled/ESM1.5/cable_surface_types.F90
  src/offline/cable_surface_types.F90
  src/offline/cbl_model_driver_offline.F90
  src/params/grid_constants_cbl.F90
  src/science/canopy/cbl_SurfaceWetness.F90
  src/science/canopy/cbl_init_wetfac_mod.f90
  src/science/casa-cnp/casa_variable.F90
  src/science/gw_hydro/cable_gw_hydro.F90
  src/science/roughness/cable_roughness.F90
  src/science/soilsnow/cbl_surfbv.F90
Labels: priority:high

#481 esm15 flag to calculate effective LAI
  src/science/roughness/cable_roughness.F90
Labels: quick, priority:high

#493 Add logn back to the cable nml
  offline/cable_driver.F90
Labels: bug
